title: Jacob Seifert, Ph.D.
description: Software and Algorithms Architect developing inspection instruments at the intersection of computational imaging, optics, machine learning, and engineering leadership.
theme: jekyll-theme-minimal
